# This template is used to create backend secrets.
# You can apply this manually:
# kubectl apply -f secret.yaml
# Keep this file hidden and out of source control.

apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: campus-help-desk
type: Opaque
stringData:
  NODE_ENV: "production"
  PORT: "5000"
  DB_HOST: "campus-help-desk-database.cvwygyygw2df.ap-south-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_USER: "postgres"
  DB_PASSWORD: "kZhA*Q.BzHgzp#n4EJc~E#>p|a4k"
  DB_SSL: "true"
  JWT_SECRET: "your_super_secret_jwt_key_here"
  JWT_EXPIRE: "7d"
